import { ArrowRight, BarChart3, Compass, FileClock, Gauge, ShieldCheck, Sparkles } from "lucide-react";
import { Logo } from "@/components/logo";
import { Button } from "@/components/ui";
import { ForecastChart } from "@/components/forecast-chart";

export default function LandingPage() {
  return <>
    <header className="site-header"><Logo/><nav className="site-nav"><a href="#product">Product</a><a href="#pricing">Pricing</a><a href="#faq">FAQ</a></nav><div className="site-actions"><Button href="/sign-in" variant="ghost">Sign in</Button><Button href="/sign-up">Start planning</Button></div></header>
    <main>
      <section className="hero"><span className="hero-kicker"><i/>Built for independent businesses</span><h1>Know what you can <em>safely spend.</em></h1><p>FlowPilot turns invoices, expenses, and tax obligations into one clear daily forecast—so every financial decision starts with confidence.</p><div className="hero-actions"><Button href="/sign-up">Build your forecast <ArrowRight size={16}/></Button><Button href="/dashboard" variant="secondary">Explore the demo</Button></div><div className="trust-line">No credit card · Set up in under 10 minutes · Your data stays yours</div></section>
      <div className="preview-wrap"><div className="preview"><aside className="preview-side"><Logo inverse/><span>Overview</span><span>Transactions</span><span>Invoices</span><span>Forecast</span><span>Scenarios</span></aside><div className="preview-main"><div className="preview-top"><div><small>FRIDAY, 20 JUNE</small><h3>Good morning, Ahmed</h3></div><div className="preview-avatar">AH</div></div><div className="preview-grid"><div className="preview-safe"><small>SAFE TO SPEND TODAY</small><strong>SAR 84,600</strong><p>↑ SAR 12,400 since last Friday</p></div><div className="preview-metric"><small>30-DAY OUTLOOK</small><strong>SAR 145,800</strong><p>Healthy · above your buffer</p></div><div className="preview-chart"><header><div><h4>Your cash horizon</h4><small>Expected balance · 90 days</small></div><span className="hero-kicker"><i/>Healthy</span></header><ForecastChart/></div></div></div></div></div>
      <section className="section" id="product"><div className="section-head"><div><p className="eyebrow">Clarity, every morning</p><h2>See the business you actually have—not the bank balance illusion.</h2></div><p>FlowPilot connects what has happened with what is likely to happen, then shows the assumptions behind every number.</p></div><div className="feature-grid">
        <Feature icon={<Gauge/>} title="One safe number" text="Know what remains after payroll, taxes, upcoming bills, your operating buffer, and forecast risks."/>
        <Feature icon={<BarChart3/>} title="A daily cash horizon" text="Scan expected, optimistic, and conservative balances across the next 30, 60, or 90 days."/>
        <Feature icon={<FileClock/>} title="Invoices with memory" text="Prediction adjusts as invoices age, payment dates are confirmed, and clients build a payment history."/>
        <Feature icon={<Compass/>} title="Decisions before commitments" text="Model a new hire, equipment purchase, price change, or late-paying client before cash leaves the account."/>
        <Feature icon={<ShieldCheck/>} title="Tax money stays reserved" text="Automatically separate estimated tax from genuinely available cash, with every estimate clearly labeled."/>
        <Feature icon={<Sparkles/>} title="Actions, not anxiety" text="Get a short, prioritized list: chase this invoice, move that purchase, or hold spending until Friday."/>
      </div></section>
      <section className="quote"><div className="quote-inner"><blockquote>“I stopped checking three spreadsheets before saying yes to a purchase. FlowPilot gives me the answer while the decision still matters.”</blockquote><p>RANA AL-SALEH · FOUNDER, NORTHLINE STUDIO</p></div></section>
      <section className="section" id="pricing"><div className="section-head"><div><p className="eyebrow">Simple pricing</p><h2>Less than the cost of one uncertain decision.</h2></div></div><div className="pricing-grid"><Price name="Solo" price="79" text="For independent professionals" items={["90-day cash forecast","Invoice tracking","CSV bank imports"]}/><Price featured name="Studio" price="179" text="For small teams and agencies" items={["Everything in Solo","Scenario simulator","5 team members","PDF reports"]}/><Price name="Business" price="399" text="For growing operations" items={["Everything in Studio","Unlimited members","Role-based access","Priority support"]}/></div></section>
      <section className="section faq" id="faq"><p className="eyebrow">Questions, answered</p><h2>Before you trust us with the numbers.</h2>{[ ["Does FlowPilot move or hold my money?","No. FlowPilot is a planning layer. It reads imported or connected financial data and never initiates payments."], ["Are tax reserves tax advice?","No. Tax reserves are clearly labeled estimates based on the percentage you configure. Your accountant remains the source of tax advice."], ["How does invoice prediction work?","We start with transparent status-based confidence levels, then show exactly how each expected payment contributes to your forecast."], ["Can my team use it?","Yes. Studio and Business plans support organizations with role-based access for owners, admins, members, and viewers."] ].map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</section>
      <section className="section"><div className="final-cta"><p className="eyebrow">Your next 90 days, made visible</p><h2>Make the next decision with the full picture.</h2><p>Start with your current balance. Your first forecast takes about ten minutes.</p><Button href="/onboarding">Build your forecast <ArrowRight size={16}/></Button></div></section>
    </main><footer className="site-footer"><Logo/><span>© 2026 FlowPilot. Forecasts are estimates, not financial advice.</span></footer>
  </>;
}

function Feature({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <article className="feature">{icon}<h3>{title}</h3><p>{text}</p></article>}
function Price({name,price,text,items,featured=false}:{name:string;price:string;text:string;items:string[];featured?:boolean}){return <article className={`price-card ${featured?"featured":""}`}>{featured&&<p className="eyebrow">Most popular</p>}<h3>{name}</h3><div className="price">SAR {price}<small>/mo</small></div><p>{text}</p><ul>{items.map(x=><li key={x}>{x}</li>)}</ul><Button variant={featured?"primary":"secondary"}>Choose {name}</Button></article>}
